version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  # cockroach:
  #   image: cockroachdb/cockroach
  #   ports:
  #    - "26257:26257"
  #    - "8080:8080"
  #   networks:
  #     - postgres
  #   command: start-single-node --insecure
  #   volumes:
  #    - "${PWD}/cockroach-data/cockroach:/cockroach/cockroach-data"

volumes:
  postgres: